server:
  port: 3000

db: 
  type: "postgres"
  port: 5432
  database: "StudentMgmtDb"

smtp:
  server: "smtp_server"
  useSecureConnection: true
  username: "user@example.com"
  password: "example_password"
  port: 465

jwt:
  expiresIn: 3600

logger:
  requests: false
