server:
  port: 3000

db: 
  type: "postgres"
  port: 5432
  database: "StudentMgmtDb"

smtp:
  server: "smtp_server"
  useSecureConnection: true
  username: "user@example.com"
  password: "example_password"
  port: 465

authSystem:
  url: "http://147.172.178.30:8080/api/v0/authenticate/check"

jwt:
  expiresIn: 36000

logger:
  requests: false
  dbErrors: false
