db: 
  host: "localhost"
  username: "postgres"
  password: "admin"
  synchronize: true
  dropSchema: true

smtp:
  server: "smtp_server"
  useSecureConnection: true
  username: "user@example.com"
  password: "example_password"
  port: 465

authSystem:
  url: "http://147.172.178.30:8080/api/v0"


jwt:
  secret: "jwt-dev-secret"

logger:
  requests: false
  dbErrors: true
